### ISSUE TITLE
Bluetooth or WiFi? How to use from an iPhone (Apple USB restrictions)

### ISSUE THREAD

**Issue by brandonros** [jglim/OkayCAN#1]

**Comment by jglim** [comment]
There's a WiFi (over http) demo [available here](https://github.com/jglim/OkayCAN/tree/main/Firmware/Examples/OkayCAN_OBD). With a proper PWA setup, it should be possible to have a web application behave like a native iOS application with some constraints. 

As far as I understand, USB on iOS isn't accessible to most folks as it requires MFi on top on an existing developer account. BLE isn't an option unless running from a native app ($99/year).

**Comment by brandonros** [comment]
https://apps.apple.com/us/app/webble/id1193531073

**Comment by brandonros** [comment]
BLE is a bit better I think for performance (like flashing). See https://github.com/bri3d/esp32-isotp-ble-bridge
