### ISSUE TITLE
Send consecutive frame 

### ISSUE THREAD

**Issue by Liu-jingyu-CN** [jglim/OkayCAN#3]
Thanks a lot for this project, I have successfully try to read gateway.
But when I need to do more in-depth operations, I need to Send consecutive frame.
Perform other service operations by informing the gateway diagnostic instrument to access.
For example, use 2E service to send a piece of RAW CAN data to modify vehicle data.
Is it possible to add a demo that Send consecutive frame ？

00007937 TX ISO-TP: 22 F1 97 
0000794B RX ISO-TP: 62 F1 97 47 57 20 4D 51 42 20 54 54 33 20 20 20 
Received VW System Name: GW MQB TT3   
00007D20 TX ISO-TP: 22 F1 91 
00007D3D RX ISO-TP: 62 F1 91 38 53 30 39 30 37 34 36 38 46 20 
Received VW ECU Hardware Number: 8S0907468F 
00008109 TX ISO-TP: 22 F1 87 
00008125 RX ISO-TP: 62 F1 87 38 53 30 39 30 37 34 36 38 4E 20 
Received VW_Spare Part Number: 8S0907468N 
000084F2 TX ISO-TP: 22 F1 A3 
000084F9 RX ISO-TP: 62 F1 A3 30 32 34 
Received Hardware Version Number: 024
000088DB TX ISO-TP: 22 F1 89 
000088E1 RX ISO-TP: 62 F1 89 30 35 30 32 
Received Software Version Number: 0502
00008CC4 TX ISO-TP: 22 F1 9E 
00008CE7 RX ISO-TP: 62 F1 9E 45 56 5F 47 61 74 65 77 43 6F 6E 74 69 41 55 33 33 58 00 
Received ASAM ODX File Identifier: EV_GatewContiAU33X
000090AD TX ISO-TP: 22 F1 A2 
000090BB RX ISO-TP: 62 F1 A2 30 31 33 30 32 36 
Received ASAM ODX File Version: 013026
00009496 TX ISO-TP: 22 06 00 
000094C1 RX ISO-TP: 62 06 00 03 01 00 04 3F 08 59 00 5B 00 00 4A 1A 0B 00 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 
Received VW Coding Value: 03 01 00 04 3F 08 59 00 5B 00 00 4A 1A 0B 00 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 
0000987F TX ISO-TP: 22 04 90 
000099FD RX ISO-TP: 62 04 90 21 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 3A 2D 2D 2A 2D 2D 2E 2D 2A 2D 2D 2A 2D 2D 2D 2D 2D 2A 2A 2A 1A 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 3A 2D 2D 2A 2D 2D 2E 2D 2A 2D 2D 2A 2A 1A 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 3A 2D 2D 2A 2D 2D 2E 2D 2A 2D 2D 2A 2A 21 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 3A 2D 2D 2A 2D 2D 2E 2D 2A 2D 2D 2A 2D 2D 2D 2D 2D 2A 2A 2A 1A 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 3A 2D 2D 2A 2D 2D 2E 2D 2A 2D 2D 2A 2A 1A 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 3A 2D 2D 2A 2D 2D 2E 2D 2A 2D 2D 2A 2A 21 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 3A 2D 2D 2A 2D 2D 2E 2D 2A 2D 2D 2A 2D 2D 2D 2D 2D 2A 2A 2A 1A 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 3A 2D 2D 2A 2D 2D 2E 2D 2A 2D 2D 2A 2A 1A 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 2D 3A 2D 2D 2A 2D 2D 2E 2D 2A 2D 2D 2A 2A 
Received Battery Historical Data: 
!-------------:--*--.-*--*-----***␚-------------:--*--.-*--**␚-------------:--*--.-*--**
!-------------:--*--.-*--*-----***␚-------------:--*--.-*--**␚-------------:--*--.-*--**
!-------------:--*--.-*--*-----***␚-------------:--*--.-*--**␚-------------:--*--.-*--**
00009C68 TX ISO-TP: 22 2A 26 
00009C9B RX ISO-TP: 62 2A 26 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Gateway Component List allocation: 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by jglim** [comment]
Hello,

Thanks for trying out the project. The included examples are supported by https://github.com/lishen2/isotp-c/ , which should support automatic frame segmentation. 

In the below example, the buffer in `transport_tx_buffer` can be filled with more content (remember to change `content_length` too), and it should be automatically be broken into first/consecutive frames during transmission. 

https://github.com/jglim/OkayCAN/blob/24859feef76e1b3540869f00db903b38f7d8b79d/Firmware/Examples/OkayCAN_GettingStarted/src/main.cpp#L123
